version: '3.4'

services:
  mtclient_1:
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=65436
      - SCALE_NUM=1
    image: mtclient
    volumes:
      - ./scaledata:/scaledata
  mtclient_2:
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=65438
      - SCALE_NUM=2
    image: mtclient
    volumes:
      - ./scaledata:/scaledata
