version: '3.4'

services:
  mtclient_1:
    image: mtclient
    restart: always
    depends_on:
      - db
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=1035
      - SCALE_NUM=1
    volumes:
      - ./scaledata:/scaledata
      - ./script:/usr/src/app/script

  mtclient_2:
    image: mtclient
    restart: always
    depends_on:
      - db
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=1035
      - SCALE_NUM=2
    volumes:
      - ./scaledata:/scaledata
      - ./script:/usr/src/app/script

  db:
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_pwd
      - MYSQL_DATABASE=mt_scale
      - MYSQL_USER=zsh
      - MYSQL_PASSWORD=zshmt
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080
