version: '3.4'

services:
  mtclient_1:
    image: mtclient-s
    restart: always
    depends_on:
      - db
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=1038
      - SCALE_NUM=1
    volumes:
      - ./scaledata:/scaledata
      - ./script:/usr/src/app/script

  mtclient_2:
    image: mtclient-s
    restart: always
    depends_on:
      - db
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=1038
      - SCALE_NUM=2
    volumes:
      - ./scaledata:/scaledata
      - ./script:/usr/src/app/script

  mtclient_3:
    image: mtclient-s
    restart: always
    depends_on:
      - db
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=1038
      - SCALE_NUM=3
    volumes:
      - ./scaledata:/scaledata
      - ./script:/usr/src/app/script

  mtclient_4:
    image: mtclient-s
    restart: always
    depends_on:
      - db
    environment:
      - SCALE_HOST=192.168.0.100
      - SCALE_PORT=1038
      - SCALE_NUM=4
    volumes:
      - ./scaledata:/scaledata
      - ./script:/usr/src/app/script

  db:
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_pwd
      - MYSQL_DATABASE=mt_scale
      - MYSQL_USER=zsh
      - MYSQL_PASSWORD=zshmt
    volumes:
      - ./dbdata:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    restart: 'no'
    ports:
      - 8080:8080
